version: '3.5'

services:
  # proxy:
  #   image: nginx:alpine
  #   container_name: proxy
  #   ports:
  #     - '1234:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: 'unless-stopped'
  #   networks:
  #     - backend
  # server:
  #   build:
  #     context: ./
  #     target: development-build-stage
  #     dockerfile: Dockerfile
  #   container_name: server
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   restart: 'unless-stopped'
  #   networks:
  #     - backend
  #   links:
  #     - mongo
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo:4.4.1 
    container_name: db_mongo
    restart: always
    volumes:
      - ./mongodata:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis/redis-stack
    container_name: "redis"
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    networks:
      - "redisnet"
    volumes:
      - ./data:/data
    restart: always
    networks:
      - redisnet

networks:
  redisnet: 
    driver: bridge

